package com.nibblersystems.otro2048.controler;

public class ColumnaCuadrados {

    //EN ESTA CLASE HAY QUE DESARROLLAR TODO LO QUE HACE EL ARRNUMEROS, SUMAR IDICES, COMPARAR INDICES,
    //DADO EL ARRAY DE 4 NUMEROS, SUBIR LOS NUMEROS, DETERMINAR PRIMER PAR IGUALES, SEGUNDO PAR IGUALES
    // TRES IGUALES, ETC


}
